author = "Michelle J Levine"
baseURL = "http://michellejl.com/"
copyright = "&copy; Copyright 2018 Michelle J Levine"
languageCode = "en-us"
pygmentsCodefences = true
pygmentsOptions = "linenos=table"
pygmentsUseClasses = true
theme = "magical"
title = "Michelle JL"
[[menu.footer]]
identifier = "resources"
name = "Resources"
url = "/resources/"
weight = 2
[[menu.footer]]
identifier = "about"
name = "About"
url = "/about/"
weight = 1
[[menu.main]]
identifier = "resources"
name = "Resources"
url = "/resources/"
weight = 5
[[menu.main]]
identifier = "writing"
name = "Writing"
url = "/writing/"
weight = 4
[[menu.main]]
identifier = "teaching"
name = "Speaking"
url = "/teaching/"
weight = 3
[[menu.main]]
identifier = "coding"
name = "Coding"
url = "/coding/"
weight = 2
[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 1
[params]
dateformat = "January 2, 2006"
[params.author]
codepen = "michellejl"
github = "michellejl"
gravatar = "michelle@michellejl.com"
instagram = "spacecadetmj"
linkedin = "michellejl"
name = "Michelle J Levine"
twitter = "michellejlevine"
[taxonomies]
category = "categories"
series = "series"
tag = "tags"
