---
hide_body: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: date
  label: Date
  type: text
  hidden: false
  default: 
- name: draft
  label: Draft
  type: boolean
  hidden: false
  default: true
- name: Description
  label: Description
  type: text
  hidden: false
  default: ''
- name: Tags
  label: Tags
  type: list
  hidden: false
  default: []
- name: Categories
  label: Categories
  type: list
  hidden: false
  default: []
- name: featuredImg
  label: Featuredimg
  type: text
  hidden: false
  default: ''
